---
development:
  dialect: postgres
  database: streamer_development
  user: postgres
  password: postgres
  host: 192.168.1.190
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@192.168.1.190:5432/streamer_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@192.168.1.190:5432/streamer_production?sslmode=disable"}}
