Vagrant.configure("2") do |config|
  config.vm.box = "nickcharlton/postgres"
  config.vm.box_version = "2.0.0.20150705162212"
  config.vm.network "public_network", bridge: "Intel(R) 82579LM Gigabit Network Connection"

  config.vm.provider "virtualbox" do |v|
    v.name = "postgres"
  end
end
